linters:
  enable-all: true
  disable:
#    - depguard
#    - gofumpt
#    - err113
#    - goimports
#    - wrapcheck
#    - errcheck
#    - gosec
#    - forcetypeassert
#    - exhaustruct
#    - revive
#    - gochecknoinits
#    - noctx
#    - rowserrcheck
#    - gochecknoglobals
#    - sqlclosecheck
