# Defines the configuration version.
# The only possible value is "2".
version: "2"

linters:
  # Default set of linters.
  # The value can be:
  # - `standard`: https://golangci-lint.run/usage/linters/#enabled-by-default
  # - `all`: enables all linters by default.
  # - `none`: disables all linters by default.
  # - `fast`: enables only linters considered as "fast" (`golangci-lint help linters --json | jq '[ .[] | select(.fast==true) ] | map(.name)'`).
  # Default: standard
  default: none
  # Enable specific linter.
  enable:
    - staticcheck
    - govet
    - unconvert
    - gosec
    - gocyclo
    - dupl
    - misspell
    - unparam
    - ineffassign
    - gochecknoinits
    - gocritic
    - nakedret
    - prealloc
    - unused
    - dogsled
    - gocognit
    - noctx
    - testpackage
    - lll
    - errcheck
