root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o api-gateway ./cmd/api-gateway"
bin = "api-gateway"
run = "./api-gateway"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
delay = 1000

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
