version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: subscription-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - pgdata-subscription:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - weather-net

  subscription-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: subscription-service
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - weather-net

volumes:
  pgdata-subscription:

networks:
  weather-net:
    external: true
    name: software-engineering-school-5-0-kenobichek_default 