global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "subscription-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["subscription-service:8428"]
