version: '3.8'
services:
  notification-service:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - weather-net

networks:
  weather-net:
    external: true
    name: software-engineering-school-5-0-kenobichek_default
