version: '3.8'
services:
  notification-service:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
    networks:
      - weather-net

networks:
  weather-net:
    external: true
    name: software-engineering-school-5-0-kenobichek_default
