FROM golang:latest

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
COPY .air.toml ./

RUN mkdir -p /app/tmp && chmod 777 /app/tmp

CMD ["air", "-c", ".air.toml"]