global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Your Go application (if you add metrics endpoint later)
  - job_name: 'weather-api'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s
    # Uncomment if you add basic auth to your metrics endpoint
    # basic_auth:
    #   username: prometheus
    #   password: your_password

  # Node Exporter (optional - for system metrics)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # PostgreSQL Exporter (optional - for database metrics)
  # - job_name: 'postgres-exporter'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187'] 