version: '3.8'
services:
  weather-service:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - weather-net

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - weather-net


networks:
  weather-net:
    external: true
    name: software-engineering-school-5-0-kenobichek_default 
