name: golangci-lint
on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - api-gateway
          - notification-service
          - subscription-service
          - weather-service
    steps:
      - uses: actions/checkout@v4
      - name: Run golangci-lint on ${{ matrix.service }}
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: internal/services/${{ matrix.service }}