name: golangci-lint
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    container:
      image: golang:1.24-alpine
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1